pcdshub/whatrecord

MANIFEST.in
Makefile
requirements.txt
setup.py
src/whatrecord/asyn.py
src/whatrecord/bin/main.py
src/whatrecord/bin/server.py
src/whatrecord/common.py
src/whatrecord/db.py
src/whatrecord/format.py
src/whatrecord/gateway.py
src/whatrecord/graph.py
src/whatrecord/iocsh.pyx
src/whatrecord/macro.pyx
src/whatrecord/schema.py
src/whatrecord/server/__init__.py
src/whatrecord/server/html/database.html
src/whatrecord/server/html/index.html
src/whatrecord/server/html/script.html
src/whatrecord/server/html/whatrec.html
src/whatrecord/server/server.py
src/whatrecord/server/static/style.css
src/whatrecord/shell.py

Fair warning: am not good at modern web stuff, avert your eyes.
(But this Vue.js stuff seems alright, I suppose)

ENH: add server

---

.travis.yml
conda-recipe/meta.yaml
dev-requirements.txt
requirements.txt
whatrecord/bin/main.py
whatrecord/bin/parse.py
whatrecord/format.py
whatrecord/shell.py

* Brought apischema to conda-forge this morning
* Cython -> not `noarch` -> custom travis config
Wanted to see how this runs, but will finish later today during my allotted _research time_

CI: attempt after adding necessary requirements to conda-forge

---

.flake8
.gitignore
frontend/src/components/dictionary-table.vue
frontend/src/components/script-line.vue
frontend/src/views/iocs.vue
whatrecord/__init__.py
whatrecord/_whatrecord/iocsh.pyx
whatrecord/bin/parse.py
whatrecord/common.py
whatrecord/db.py
whatrecord/grammar/db.v3.lark
whatrecord/grammar/db.v4.lark
whatrecord/graph.py
whatrecord/iocmanager.py
whatrecord/iocsh.py
whatrecord/server/server.py
whatrecord/shell.py
whatrecord/tests/iocs/v3_ioc_a/ioc_a.db
whatrecord/tests/iocs/v3_ioc_a/st.cmd
whatrecord/tests/iocs/v3_softIoc.dbd
whatrecord/tests/test_bin_parse.py
whatrecord/tests/test_pva_parsing.py
whatrecord/tests/test_v3_parsing.py

Closes #37  - this was unexpectedly easy
Closes #30 
* Revisited parallel loading, this time with `concurrent.futures`; overall loading takes longer than serialization/deserialization (fortunately) so this is a net win when loading hundreds of IOCs into the whatrecord server
* Found some grammar oddities, a problem for another day
* Adds some more tests, an R3.15 IOC + dbd
* Miscellaneous fixes + cleanups from the past few days

REF: parallel loading, V3 db loading, and more

---

Makefile
whatrecord/_whatrecord/macro.pyx
whatrecord/common.py
whatrecord/db.py
whatrecord/graph.py
whatrecord/shell.py
whatrecord/tests/conftest.py
whatrecord/tests/iocs/fake_ad/st.cmd
whatrecord/tests/iocs/ioc_a/st.cmd
whatrecord/tests/iocs/ioc_b/st.cmd
whatrecord/tests/iocs/ioc_c/st.cmd
whatrecord/tests/iocs/ioc_d/ioc.db
whatrecord/tests/iocs/ioc_d/st.cmd
whatrecord/tests/iocs/pva_misc/st.cmd
whatrecord/tests/iocs/pva_simple/st.cmd
whatrecord/tests/iocs/v3_ioc_a/st.cmd
whatrecord/tests/test_bin_parse.py
whatrecord/tests/test_graph.py
whatrecord/tests/test_macro.py
whatrecord/tests/test_pva_parsing.py
whatrecord/tests/test_serialization.py

* Better macro handling with tests
* Better graph support with tests
* Alias handling in graphs
* Forgotten generic serialization test sitting in my local tests directory

ENH: better macro, graph, alias support

---

frontend/Makefile
frontend/package.json
frontend/src/App.vue
frontend/src/components/epics-format-record.vue
frontend/src/components/searchbar.vue
frontend/src/router.js
frontend/src/store.js
frontend/src/views/happi.vue
frontend/src/views/iocs.vue
frontend/src/views/pv_relations.vue
frontend/src/views/whatrec.vue
frontend/yarn.lock
setup.py
whatrecord/bin/info.py
whatrecord/bin/lint.py
whatrecord/bin/main.py
whatrecord/bin/parse.py
whatrecord/bin/server.py
whatrecord/common.py
whatrecord/db.py
whatrecord/format.py
whatrecord/graph.py
whatrecord/server/common.py
whatrecord/server/server.py
whatrecord/shell.py
whatrecord/tests/test_bin_lint.py

* Miscellaneous frontend fixes
* Start of `whatrecord lint` tool
* Miscellaneous fixes here and there
At best, this is a "WIP" set of features, but I'm good enough with how it works for now to merge. More on these later, probably.
Partially addresses #47

ENH: PV graph interactive on frontend

---

frontend/src/components/epics-format-record.vue
frontend/src/components/recordinfo.vue

ENH: show info fields and aliases in epics-format-record

---

frontend/src/components/recordinfo.vue
frontend/src/components/searchbar.vue
frontend/src/router.js
frontend/src/store.js
frontend/src/views/happi.vue
frontend/src/views/iocs.vue
frontend/src/views/logs.vue
frontend/src/views/pv_relations.vue
frontend/src/views/script-view.vue
frontend/src/views/whatrec.vue
whatrecord/common.py
whatrecord/server/common.py
whatrecord/server/server.py

Step in the right direction:
* Moderately less apparent that I'm clueless about frontend development
* Some stale code removed

MNT: frontend cleanup and fixup - getting a bit better

---

Makefile
frontend/src/components/ioc-info.vue
frontend/src/components/recordinfo.vue
frontend/src/components/searchbar.vue
frontend/src/router.js
frontend/src/views/iocs.vue
frontend/src/views/pv_relations.vue

Consistent rendering of IOC info in recordinfo or ioc view: <img width="1418" alt="image" src="https://user-images.githubusercontent.com/5139267/126412745-d9ab9312-4261-42ee-8475-08f5483c4f46.png">
PV map is still not great, but it's getting closer to what I'd like it to be:

MNT: more frontend fixups

---

MANIFEST.in
frontend/src/components/dictionary-table.vue
frontend/src/components/epics-format-record.vue
frontend/src/components/recordinfo.vue
src/_whatrecord/common.py
src/_whatrecord/iocsh.pyx
whatrecord/grammar/streamdevice.lark
whatrecord/iocsh.py
whatrecord/shell.py
whatrecord/streamdevice.py
whatrecord/tests/iocs/streamdevice/example.proto
whatrecord/tests/iocs/streamdevice/hex.proto
whatrecord/tests/iocs/streamdevice/st.cmd
whatrecord/tests/iocs/streamdevice/test.db
whatrecord/tests/iocs/streamdevice/test.proto
whatrecord/tests/test_stcmd.py
whatrecord/tests/test_streamdevice.py

* Parse StreamDevice protocol files (1100/1105 I have sitting on my laptop)
* Add record metadata based on the specific protocol for the given record
* Add basic test suite for it with sample IOC
* May be some stray lark Tokens hiding in there from the transformer
* Frontend needs a lot of work, but it's got all the necessary bits at least
Closes #40
click context to get

ENH: StreamDevice protocol parsing and record metadata

---

conda-recipe/meta.yaml
dev-requirements.txt
frontend/src/components/dictionary-table.vue
frontend/src/components/epics-format-field.vue
frontend/src/components/epics-format-record.vue
frontend/src/components/gateway-matches.vue
frontend/src/components/recordinfo.vue
frontend/src/components/script-context-link.vue
frontend/src/components/script-context-one-link.vue
frontend/src/components/script-line.vue
frontend/src/components/searchbar.vue
frontend/src/store.js
frontend/src/views/script-view.vue
src/_whatrecord/common.py
whatrecord/bin/server.py
whatrecord/common.py
whatrecord/db.py
whatrecord/iocsh.py
whatrecord/server/common.py
whatrecord/server/server.py
whatrecord/shell.py
whatrecord/tests/conftest.py
whatrecord/tests/test_bin_parse.py
whatrecord/tests/test_serialization.py
whatrecord/tests/test_server_handler.py
whatrecord/tests/test_server_state.py
whatrecord/tests/test_v3_parsing.py

Closes #58 
Closes #13
Closes #22 
Of note - tooltips for fields:

MNT: miscellaneous fixes and tweaks

---

MANIFEST.in
frontend/src/components/epics-format-record.vue
whatrecord/access_security.py
whatrecord/common.py
whatrecord/db.py
whatrecord/gateway.py
whatrecord/grammar/access_security.lark
whatrecord/streamdevice.py
whatrecord/tests/access.acf
whatrecord/tests/example.acf
whatrecord/tests/test_access.py
whatrecord/tests/test_v3_parsing.py
whatrecord/transformer.py

Seemingly big PR, but most of it comes from the ACF files I'm including here.
* Access security parsing
* Addition of transformer helpers
* Removed some awful db parsing methods and replaced/simplified them; structural changes will have an impact on frontend display most likely (so consider this a WIP - more tomorrow)

Access security parsing and more cleanup

---

frontend/src/components/script-line.vue
whatrecord/common.py
whatrecord/plugins/gdb_binary_info.py
whatrecord/shell.py

ENH: gdb plugin binary info source location context

---

MANIFEST.in
whatrecord/common.py
whatrecord/db.py
whatrecord/dbtemplate.py
whatrecord/grammar/dbtemplate.lark
whatrecord/grammar/msi-sub.lark
whatrecord/shell.py
whatrecord/streamdevice.py
whatrecord/tests/iocs/db/basic_asyn_motor.db
whatrecord/tests/iocs/db/test.substitutions
whatrecord/tests/iocs/db/test.substitutions.expanded
whatrecord/tests/t1-include.txt
whatrecord/tests/test_dbtemplate.py

* Grammar and template loading
* May not be complete or 100% correct (msi doesn't use a grammar for the `-S` portion)
* Not fully tested; more tests will likely follow
* Sum of a few distracted days/evenings; not entirely happy with how this one turned out
msi format is way more complicated than I had expected...

ENH: dbLoadTemplate and msi -S substitution grammar

---

whatrecord/bin/parse.py
whatrecord/common.py
whatrecord/db.py
whatrecord/format.py
whatrecord/gateway.py
whatrecord/shell.py
whatrecord/tests/test_bin_parse.py
whatrecord/tests/test_gateway.py

ENH: add support for other formats with 'whatrecord parse'

---

.gitignore
frontend/src/components/recordinfo.vue
frontend/src/store.js
frontend/src/views/pv_relations.vue
whatrecord/client.py
whatrecord/server/common.py
whatrecord/server/server.py
whatrecord/tests/test_server_handler.py

Addresses part of #82 
* API URLs were a well-intentioned-but-bad-idea mess
* Relatively better now
* Frontend and Python client updated appropriately

REF: clean and rework web API URLs

---

MANIFEST.in

Requirements text files were missing from `MANIFEST.in`.
Attempts to address #98 
It will be, once it's on PyPI.

BLD: fix MANIFEST

---

whatrecord/plugins/happi.py

Ref https://github.com/pcdshub/pcdsdevices/issues/885
pcdsdevices needs no fixing with this. It's unclear of the right path forward there.
Regenerated `happi.json` for `happi-to-confluence` with this code.

FIX: happi plugin fixes for GroupDevice

---

.travis.yml
conda-recipe/meta.yaml
pyproject.toml
requirements.txt
whatrecord/common.py
whatrecord/db.py
whatrecord/graph.py
whatrecord/plugins/happi.py
whatrecord/snl.py
whatrecord/tests/test_bin_parse.py
whatrecord/tests/test_graph.py
whatrecord/tests/test_serialization.py
whatrecord/tests/test_v3_parsing.py

Initial attempt at fixing at least one level of `dotted_name` for a given signal.
[This PR](https://github.com/pcdshub/atef/pull/23) showed that GroupDevice handling is imperfect here, as we still miss part of the attribute name.
* Pay off some technical debt
* Adjusting for newer releases of graphviz and apischema (closes #110)
* Fixes some CI-related issues
* Fixes build requirements
* Fixes deprecation warnings in test suite
* Fixes some type annotations
* Run once on a local atef/whatrecord/pcdsdevices install
* Test suite

FIX: happi plugin - GroupDevice + pay off some technical debt

---

README.rst

* A few more screenshots (already pushed as part of the `assets` branch - keeping the master branch history smaller)
* A couple `jq` examples

DOC: a few more README screenshots

---

whatrecord/plugins/happi.py

Invalid containers in the happi database can cause the plugin to stop describing it entirely.
Use `SearchResult` to work around upstream `dict(client)` issue.
Closes #150 
Locally with happi-to-confluence development
Issue and PR

FIX: happi plugin with invalid container in database

---

conda-recipe/meta.yaml
dev-requirements.txt
whatrecord/tests/test_server_handler.py

`epicsmacrolib` is now on conda-forge. Let's see if whatrecord conda env tests work now.
conda tests are currently failing
Closes #156

BLD: epicsmacrolib is now on conda-forge

---

conda-recipe/meta.yaml

BLD: use maintained lark conda-forge package
