pcdshub/whatrecord

- MANIFEST.in
- conda-recipe/meta.yaml
- requirements.txt
- src/whatrecord/gateway.py
- src/whatrecord/grammar/access_security.lark
- src/whatrecord/grammar/db.lark
- src/whatrecord/grammar/dbtemplate.lark
Anecdotally, this is successfully lexing/parsing some regular databases plus those with json mixed in.
The latter is needed for qsrv, like follows:
```
record(aao, "$(N)A") {
field(FTVL, "DOUBLE")
field(NELM, "10")
info(Q:group, {
"$(N)Tbl":{
"value.A":{+type:"plain", +channel:"VAL", +putorder:1}
}
})
field(TPRO, "1")
}
```
In a pretty tree:
```
start
database
database_item
record
record_head
aao
"$(N)A"
record_body
record_field
field
FTVL
json_value    "DOUBLE"
record_field
field
NELM
json_value    "10"
record_field
info
Q:group
json_value
json_object
json_members
json_pair
"$(N)Tbl"
json_value
json_object
json_members
json_pair
"value.A"
json_value
json_object
json_members
json_pair
+type
json_value    "plain"
json_members
json_pair
+channel
json_value  "VAL"
json_members
json_pair …
```
> ENH: add lark grammar files - database, dbLoadTemplate, and access security

- frontend/src/App.vue
- src/whatrecord/bin/iocmanager_loader.py
- src/whatrecord/bin/main.py
First part of #20 for LCLS's purposes.
```
$ whatrec iocmanager-loader --configs iocmanager.example.cfg |head -n 15
[
{
"id": "ioc-amo-gige-01",
"host": "ioc-amo-gige01",
"port": 30011,
"dir": "ioc/amo/gigECam/R2.3.3",
"history": [
"ioc/amo/gigECam/R2.3.3",
"/reg/neh/home/sstubbs/work/amo/gigECam/current"
],
"startup_script": "/reg/g/pcds/epics/ioc/amo/gigECam/R2.3.3/iocBoot/ioc-amo-gige-01/st.cmd"
},
...
```
The original utility (which we can't import as it's not a package) uses some [unsavory techniques](https://github.com/pcdshub/IocManager/blob/39a284dbf41d84f743d78e994654f160c1337383/utils.py#L496) for loading the configs.
The parser here is less resilient and dynamic, but as the author of it, I like it a bit more than the above. Can revisit if need be.
> ENH: add iocmanager loader

- README.rst
- whatrecord/common.py
- whatrecord/db.py
- whatrecord/format.py
- whatrecord/server/server.py
- whatrecord/tests/conftest.py
- whatrecord/tests/test_bin_parse.py
Closes #34 
Partially addresses #23 
Ended up really being a `typing.Union[ForwardRef, ForwardRef]` issue with how it's handled in 3.7 vs 3.9 (and - I think - `from __future__ import annotations`, but to be honest I didn't dig much).
And it was easy enough to just rearrange the code to remove the forward reference.
Can add pypy3 to the test matrix one day
> FIX: forwardref issue with python 3.7

- frontend/src/App.vue
- frontend/src/components/recordinfo.vue
- frontend/src/router.js
- frontend/src/settings.js
- frontend/src/store.js
- frontend/src/views/happi.vue
- frontend/src/views/iocs.vue
- whatrecord/ioc_finder.py
- whatrecord/plugins/happi.py
- whatrecord/server/server.py
- whatrecord/shell.py
- whatrecord/util.py
Closes #26 👏 
Partially addresses #27 
Not finalized, as usual, but I think this isn't a ... terrible form.
I think generally, plugins should be able to - define records, annotate records, annotate IOCs.
As of now, the following is partly supported, allowing happi metadata to find its way to records, and the happi vue to generate a table of its entire set of metadata.
```python
@dataclasses.dataclass
class PluginResults:
files_to_monitor: List[str]
metadata: Any
record_to_metadata: Dict[str, Any]
@dataclasses.dataclass
class HappiPluginResults:
item_to_metadata: Dict[str, HappiItem]
record_to_item_name: Dict[str, List[str]]
item_to_records: Dict[str, List[str]]
```
Happi view of database
Happi view of single item
whatrecord indicator linking to happi
> ENH: Happi + sketch of what a server plugin might look like

- .travis.yml
- MANIFEST.in
- frontend/src/App.vue
- frontend/src/components/gateway-matches.vue
- frontend/src/components/ioc-info.vue
- frontend/src/router.js
- frontend/src/store.js
- frontend/src/views/gateway.vue
- frontend/src/views/whatrec.vue
- whatrecord/common.py
- whatrecord/gateway.py
- whatrecord/grammar/gateway.lark
- whatrecord/server/server.py
- whatrecord/shell.py
- whatrecord/tests/kfe.pvlist
- whatrecord/tests/test_gateway.py
- whatrecord/tests/test_server_handler.py
- whatrecord/tests/test_server_state.py
The gateway view and restructuring, finished up from yesterday. (More lark grammars 👏 )
Much easier to browse and search gateway rules now.
Closes #60 
And stuff that was part of the old linter functionality:
> REF: rework gateway parsing + add frontend view

- frontend/package.json
- frontend/src/components/dictionary-table.vue
- frontend/src/components/epics-format-record.vue
- frontend/src/components/recordinfo.vue
- frontend/src/components/searchbar.vue
- frontend/yarn.lock
- whatrecord/access_security.py
- whatrecord/common.py
- whatrecord/server/server.py
- whatrecord/shell.py
- whatrecord/tests/iocs/ioc_dbloadtemplate/st.cmd
- whatrecord/tests/test_bin_parse.py
Closes #70 
Load context is pretty great now:
Only remaining issue is that the frontend display of output is pretty terrible for st.cmd:
> ENH: show asg in frontend; add dbLoadTemplate support to IOC shell interpreter

- whatrecord/common.py
- whatrecord/server/server.py
Part of #82 
* Was: "load IOC metadata once; check for updates from that list periodically"
* Now: "load IOC metadata and add new metadata / update previous; check for updates from all IOCs"
> ENH: periodically check for new/updated IOC metadata with loader

- whatrecord/gateway.py
When evaluating a gateway access regex, use `fullmatch` instead of `match` to reflect the behavior of the epics gateway.
`match` will match substrings starting from the beginning of the string.
`fullmatch` will only match if the full string matches.
closes #91 
`predict_gateway_response` from `pcds-gateway-tests` for `'LAS:FS1:Angle:Shift:Ramp:Target_1MIN_AVG'` behaves as expected with this patch
N/A
> BUG: use fullmatch to evaluate gateway rules to reflect gateway behavior

- .travis.yml
- MANIFEST.in
- pyproject.toml
Closes #98 (or if it doesn't, I'll reopen it)
This appears to work locally in a clean environment.
I don't like using separate build config files, so this will take some more reworking down the line. Consider it a hotfix for today's environment build.
> BLD: use pyproject.toml to add build requirements

- .travis.yml
- MANIFEST.in
- whatrecord/bin/parse.py
- whatrecord/common.py
- whatrecord/grammar/snl.lark
- whatrecord/snl.py
- whatrecord/tests/iocs/ioc_sequencer/LICENSE
- whatrecord/tests/iocs/ioc_sequencer/sncExEntry.st
- whatrecord/tests/iocs/ioc_sequencer/sncExOpt.st
- whatrecord/tests/iocs/ioc_sequencer/sncExample.st
- whatrecord/tests/test_serialization.py
- whatrecord/tests/test_snl.py
* Adds grammar and Python classes for the EPICS sequencer's state notation language (snl, extension `.st`)
* Adds hook for `whatrecord parse` to support `.st` files
Closes #90 (I'll get around to the state transition diagrams one day)
* Test suite with example `.st` files and apischema serialization/deserialization
* Plus around 90 additional `.st` files not included in the repository
* All but those requiring a C preprocessor to take care of `#define` and such will work
* Added some tests which show how the lack of a proper preprocessor can screw things up
> ENH: EPICS sequencer state notation language (snl) grammar+parsing

- whatrecord/graph.py
I ran into this invalid one today:
`'$@lakeshore331.proto.db'` which caused
```
File "whatrecord/whatrecord/graph.py", line 233, in build_database_relations
link, field2 = link.split(".")
ValueError: too many values to unpack (expected 2)
```
This will still show an invalid record and field, but I think this is preferable to throwing it away.
> FIX: malformed links can have multiple dots

- conda-recipe/meta.yaml
- requirements.txt
* Addresses #110 
* Bumps minimum Python to 3.9+. I noticed at some point 3.7 was broken when using `Tuple[type, ...]` syntax but gave up on adhering to that. 3.7 isn't a target for us in general, but PyPy (stuck at 3.7) will no longer work. It offers significant speedups over CPython for some of the large lark grammars we have here and the corresponding apischema serialization/deserialization.
Long-term whatrecord will need some fixing - tuple handling with apischema changed from 0.15.7 to 0.16.0 and lead to much of the test suite being broken. I'm unsure at this point how much is whatrecord using the library wrong versus potential (but unlikely) apischema bugs. 
So - pin for now.
Local testing comparing apischema versions.
Linked issue.
> BLD: update pinning of apischema + Python

- conda-recipe/meta.yaml
- requirements.txt
- whatrecord/access_security.py
- whatrecord/autosave.py
- whatrecord/bin/graph.py
- whatrecord/bin/main.py
- whatrecord/bin/parse.py
- whatrecord/common.py
- whatrecord/db.py
- whatrecord/dbtemplate.py
- whatrecord/gateway.py
- whatrecord/graph.py
- whatrecord/snl.py
- whatrecord/streamdevice.py
- whatrecord/tests/test_bin_graph.py
Add command-line support for:
```
$ whatrecord graph st.cmd
$ whatrecord graph database.db
```
It'd be nice to not have to spawn up a server to investigate record links.
Output of:
```
whatrecord graph pluginROI.db  --highlight "HOPR" |dot -Tpdf -O
```
(internal link fields used here; no dbd required)
> ENH: add 'whatrecord graph' entrypoint with at least db/st.cmd support

- .travis.yml
- whatrecord/bin/graph.py
- whatrecord/bin/parse.py
- whatrecord/common.py
- whatrecord/db.py
- whatrecord/grammar/snl.lark
- whatrecord/graph.py
- whatrecord/gv_compat.py
- whatrecord/server/server.py
- whatrecord/snl.py
- whatrecord/tests/test_bin_graph.py
- whatrecord/tests/test_snl.py
* Add graphviz plotting for EPICS state notation language programs.
* Add helper base class to be used for all graphs supported by whatrecord (PVs, scripts, state notation language)
* Cleans up `whatrecord graph` entrypoint; the following are now valid:
* `whatrecord graph simple.st -o test.png`
* `whatrecord graph *.db -o test.png`
* SNL grammar somewhat round-trippable (modulo comments and formatting)
* Works, but formatting / display could use improvement
These programs can be difficult to interpret.  Even for simple cases, this can be useful.
Against a suite of programs I rounded up from existing IOCs a while back.
This PR text. And #105 
One without code:
One with code:
> ENH/FIX: state notation language graphs + misc fixes

- .pre-commit-config.yaml
- whatrecord/iocmanager.py
- whatrecord/tests/test_iocmanager_loader.py
Cron job was notifying me of failures when certain lines in configs failed to parse, with:
```
ERROR:whatrecord.iocmanager:Failed to fix up IOC manager entry
...
^
SyntaxError: unexpected EOF while parsing
```
due to user-introduced comments in the file, which are technically valid in the pseudo-Python IOC Manager config file.
Closes #126 
Included test suite which adds coverage for some previously uncovered lines in the repo.
> FIX/TST: avoid parsing commented lines in iocmanager config

- whatrecord/bin/graph.py
- whatrecord/common.py
- whatrecord/db.py
- whatrecord/graph.py
- whatrecord/tests/test_graph.py
- whatrecord/tests/test_v3_parsing.py
* Record link graphing needs some reworking, even after this gets completed
* I was hoping to get it done today, but ran out of time
* This is still probably in a better state than before, but I want to give it another look
* Test suite will fail until I get to fixing it
* The actual first user of whatrecord after over a year of being released discovered it didn't quite work as advertised 😬  
* Excuse: `whatrecord graph` command-line worked differently than the originally included `st.cmd`-backed evaluator, which would auto-load and use the dbd where necessary
Closes #125 
Interactively, with a user-provided db file
> FIX: fix and clean record graphs + arrow direction using test-suite vendored dbd files

- whatrecord/plugins/gdb_binary_info.py
GDB EPICS binary information tool should support Python 2 syntax because psbuild and others have an ancient gdb version.
Closes #129 
Briefly checked on 9.2 and 7.6.1:
```
GNU gdb (GDB) 9.2
Copyright (C) 2020 Free Software Foundation, Inc.
```
```
$ /usr/bin/gdb --version
GNU gdb (GDB) Red Hat Enterprise Linux 7.6.1-120.el7
Copyright (C) 2013 Free Software Foundation, Inc.
```
> FIX: python 2 compatibility for old gdb

- setup.py
- whatrecord/common.py
- whatrecord/tests/test_graph.py
- whatrecord/tests/test_pva_parsing.py
Ignore non str RecordField fields in `whatrecord graph`.
* Experimenting with the `lsi` record
* To set it at startup, you need to use `field(INP, ["value"])` to indicate it's an array and not a link name (per tech talk)
* Graph will fail as it only checks for PVA field references (which are described as JSON objects / `dict` in the EPICS process database)
* Parsing test added in test suite
* Record relations checked to not fail in test suite when a field is a JSON value (i.e., non-str)
PR text
> FIX: ignore non str RecordField fields in `whatrecord graph`

- .travis.yml
- dev-requirements.txt
- whatrecord/bin/graph.py
- whatrecord/db.py
- whatrecord/dbtemplate.py
- whatrecord/parse.py
- whatrecord/shell.py
- whatrecord/tests/test_v3_parsing.py
* Remove `whatrecord.LinterResults`
* Wrap lint into `whatrecord.Database` `.lint` attribute, which is a `DatabaseLint` instance
There are too many classes representing a `Database` in whatrecord; this removes one and wraps it into `Database.lint`
* Test suite
These will happen in separate PRs:
- Server needs updating
- More lint checks should be added
> REF: remove linterresults

- whatrecord/graph.py
- whatrecord/parse.py
Fix FLNK source ports and direction.
Forward link edges were inaccurately drawn with graphviz, so this PR should fix them.
Looks correct now:
> FIX: forward link edges + allow for stdin usage in `whatrecord [parse|graph]`

- whatrecord/macro.py
- whatrecord/settings.py
- whatrecord/tests/test_macro.py
* pcds-ci is failing due to long environment variable values https://app.travis-ci.com/github/pcdshub/pcds-envs/jobs/586389673#L9085
* This assertion was present largely for testing but also to let users know there was a weird limit present in the original source code but they could work around it with a different call (a bad choice in retrospect)
* The appropriate handling of "too long values" is to pass them to macro lib anyway, which clips them at the provided buffer length
* CI failures
* Additional test for macro context serialization
This PR
> REF/ENH: add settings to exclude all/certain env vars in serialization

- .github/workflows/standard.yml
https://docs.github.com/en/actions/using-workflows/reusing-workflows#passing-inputs-and-secrets-to-a-reusable-workflow
The github docs example is:
```
jobs:
call-workflow-passing-data:
uses: octo-org/example-repo/.github/workflows/reusable-workflow.yml@main
with:
config-path: .github/labeler.yml
secrets: inherit
```
pypi upload fails on auth
> CI: check if secrets inherit works for pypi upload

- conda-recipe/meta.yaml
Conda recipe needs test-requires, not test-requirements
Ran into this looking at lucid
The test suite should now have all the necessary test packages... though tests here look rough
this PR
> BLD: recipe test-requires, not test-requirements

- whatrecord/bin/parse.py
- whatrecord/macro.py
- whatrecord/parse.py
- whatrecord/tests/test_macro.py
* Add `--disable-macros` to `whatrecord parse`
* For input formats where this is possible - such as database files - macros will remain untouched/unexpanded/uninterpolated in the output format.
* That is to say, `field(DESC, "$(ABC)")` will remain as-is instead of `field(DESC, "value of abc")`
* Add `PassthroughMacroContext` which acts as a no-operation macro context but still supports all methods
Closes #164 
`whatrecord` was built around the idea of "parse files as if the IOC shell were reading them".
That means that it aims to expand (interpolate) macros in files according to the EPICS environment and fall back to the shell environment variables (at least in certain scenarios) for each file that gets parsed.
* A bit locally with some database files
* Lazily in the test suite
* Issue …
> ENH: add --disable-macros + passthrough context

- conda-recipe/meta.yaml
- dev-requirements.txt
Add `blark` as a dev/test dependency, in an attempt to reveal a test that fails on pcds-envs but doesn't run at all in the test suite here.
In pcds-envs on the weekly build, whatrecord was failing with this message:
```
_________________________ test_serialize[PlcMetadata] __________________________
cls = <class 'whatrecord.plugins.twincat_pytmc.PlcMetadata'>
@all_dataclasses
def test_serialize(cls):
>       instance = try_to_instantiate(cls)
whatrecord/tests/test_serialization.py:151: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
whatrecord/tests/test_serialization.py:123: in try_to_instantiate
type_hints = apischema.utils.get_type_hints(cls)
/home/runner/miniconda/envs/pcds-test/lib/python3.9/typing.py:1459: in get_type_hints
value = _eval_type(value, …
```
> TST: add missing dependency that reveals failing tests from pcds-envs

- frontend/package.json
- frontend/src/App.vue
- frontend/src/components/epics-format-record.vue
- frontend/src/components/gateway-matches.vue
- frontend/src/components/recordinfo.vue
- frontend/src/router.ts
- frontend/src/settings.ts
- frontend/src/stores/api.ts
- frontend/src/stores/cached.ts
- frontend/src/types/index.ts
- frontend/src/types/stream.ts
- frontend/src/views/duplicates.vue
- frontend/src/views/gateway.vue
- frontend/src/views/happi.vue
- frontend/src/views/iocs.vue
- frontend/src/views/lcls_epicsarch.vue
- frontend/src/views/logs.vue
- frontend/src/views/twincat_pytmc.vue
- frontend/src/views/whatrec.vue
- frontend/vite.config.ts
- frontend/yarn.lock
- whatrecord/server/common.py
- whatrecord/server/server.py
- whatrecord/shell.py
- whatrecord/streamdevice.py
- whatrecord/tests/test_serialization.py
* Server logs visible on serverless mode
* File viewing working on serverless mode
* To potentially revert or make configurable: using [hash mode in vue-router](https://router.vuejs.org/guide/essentials/history-mode.html#Hash-Mode) to avoid changes to our old web servers
* Had issues with axios decompressing `.json.gz` on pswww (perhaps due to my own lack of knowledge); reverted to using a separate library for decompression which should work in all cases
* Adds plugin-only mode, used in the current deployment
TODO:
* Conference is coming up
* Test deployment of serverless "plugin-only" thing is on pswww for our team to use
* Interactively
* Some in the test suite
PR
> FIX/ENH: a few more fixes for cached/offline mode + plugin only mode
